### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dw-dot** [cns-iu/ccf-organ-vr-gallery#113]
README typo 

Credits
This software is developed by [Andreas Bueckle](https://www.andreas-bueckle.com/) at the [Cyberinfrastructure for Network Science Center at Indiana University](http://cns.iu.edu/).

**Comment by andreasbueckle** [comment]
Thanks! This will be fixed the next time we pull dev into main.

----------------------------------------------
Best,
Andreas

Andreas "Andi" Bueckle, Ph.D.
Research Lead, Cyberinfrastructure for Network Science Center (CNS)
Head Coach, Sailing Club at Indiana University
Room #4024
Luddy School of Informatics, Computing, and Engineering, Indiana University
700 N Woodlawn Ave (Luddy Hall)
47408 Bloomington, IN - USA

email: ***@***.******@***.******@***.***>
web: www.andreas-bueckle.com<https://www.andreas-bueckle.com>
________________________________
From: dw-dot ***@***.***>
Sent: Tuesday, October 11, 2022 4:56:26 PM
To: cns-iu/ccf-organ-vr-gallery ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cns-iu/ccf-organ-vr-gallery] typo (Issue #113)


!&! = at

Credits
This software is developed by Andreas Bueckle<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.andreas-bueckle.com%2F&data=05%7C01%7Cabueckle%40iu.edu%7C6713f21aab2b4949eb1308daabcb2994%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C638011186309593759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zHjZYotm6Tx6wtn3qfj2mVkLOQw2HGlu%2FR7uSI85ewU%3D&reserved=0> !&! the Cyberinfrastructure for Network Science Center at Indiana University<http://cns.iu.edu/>.
