### ISSUE TITLE
Prototype wrist pockets in dev room

### ISSUE THREAD

**Issue by cqing5** [cns-iu/ccf-organ-vr-gallery#58]

**Comment by andreasbueckle** [comment]
Notes from Heidi + Rachel:
* need annotations when put into wrist pocket
* One email for all blocks per session
* Need solution to remind user of why block was selected
* Rename to tissue box? 
* Assign color
* Email sends screenshot from VR? User can add annotation
* Work with https://www.iso-form.com/?
