### ISSUE TITLE
Add local copies of organs, revamp ModelLoader for updates every 6 months to sync with HRA release

### ISSUE THREAD

**Issue by cqing5** [cns-iu/ccf-organ-vr-gallery#60]

**Comment by andreasbueckle** [comment]
Next step could be to test loading 1 GLB file in a new project and see if it works

**Comment by andreasbueckle** [comment]
Also, revamp CSVReader with TextAsset as in: https://github.com/cns-iu/ccf-organ-vr-gallery/blob/pbi-redesign-model-loader/CCF3DOrganGallery/Assets/Scripts/Obsolete/DataReader.cs

**Comment by andreasbueckle** [comment]
Organs now load when running natively on Quest 2 (GLTFUtility shaders need to be added to Always Include Shaders in player settings). CSVReader loads text as TextAsset now.
